### ISSUE TITLE
AMF refs

### ISSUE THREAD

**Issue by sunt05** [BLM-UoR/BLM#17]
add useful papers for AMF datasets.

**Comment by hamidrezaomidvar** [comment]
https://onlinelibrary.wiley.com/doi/full/10.1111/j.1365-2486.2006.01281.x 
https://nph.onlinelibrary.wiley.com/doi/full/10.1111/j.1469-8137.2008.02501.x
http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.466.3686&rep=rep1&type=pdf

**Comment by sunt05** [comment]
Just a reminder here:
we use [this plugin](https://sphinxcontrib-bibtex.readthedocs.io/en/latest/index.html) to manage bibliography of this site.
